### ISSUE TITLE
Installation failed. Unexpected end when deserializing object. Path 'Project', line 2, position 0.

### ISSUE THREAD

**Issue by kaylnaris** [Renaleteto/parkitect-tropical-trees-pack#1]
The latest release of the tropical trees mod is broken. It cannot be installed because there seems to be an error in an project file (json?). The logged error message is in the title of this issue. I've included the full log with the error message on an attempted installation of the mod via the parkitectnexus client below.

On the mod's page on parkitectnexus there are several comments (including one from me), which describe the same behaviour: http://parkitectnexus.com/assets/878790b714/tropical-trees-pack

This is a gread mod, so it would be great if it would be working again! Could you please have a look at the error and possibly fix it?

The following error messages are logged:

```
[16-05-25 22:53:37] Debug: Task status Running 15%: Installing mod 'Tropical Trees Pack'...
[16-05-25 22:53:47] Debug: Attempting to open mod stream.
[16-05-25 22:53:47] Debug: Mod archive main folder is Renaleteto-parkitect-tropical-trees-pack-e647c2b/.
[16-05-25 22:53:47] Error: Task status FinishedWithErrors 100%: Installation failed. Unexpected end when deserializing object. Path 'Project', line 2, position 0.
[16-05-25 22:53:47] Debug: Task ParkitectNexus.Data.Tasks.Prefab.InstallAssetTask ended in state FinishedWithErrors at 100%.
[16-05-25 22:53:47] Debug: Task ParkitectNexus.Data.Tasks.Prefab.InstallAssetTask process finished.
```

**Comment by kaylnaris** [comment]
I've just had a quick look at the code of this mod. As far as I could see the bug mentioned above is fixed now, but the mod doesn't compile and install because some merge conflict markers seem to have been accidentally checked in. I fixed those and submitted a merge request: https://github.com/Renaleteto/parkitect-tropical-trees-pack/pull/2

With these changes, this mod works on my local parkitect installation. 

Could you please accept the merge request and release a new version?

**Comment by kaylnaris** [comment]
wow you're fast, I can see you're working on this issue just now. I think you've just fixed the same things which I submitted as a pull request, so I think you can ignore my pull request and keep your fixed :)

**Comment by Renaleteto** [comment]
Sorry, I was being very busy trying to control anything and for some reason
I didn't see your pull request! But the mod should work now, also when
installing through parkitect nexus, it was working fine in my local
installation before the fix too, it was a git-hub problem! By the way,
thanks a lot for your suggestion and your help!
Il 26/Mag/2016 00:21, "kaylnaris" notifications@github.com ha scritto:

**Comment by kaylnaris** [comment]
Thanks a lot for the super fast fix! It now works again, I just installed the newest version of this mod. The tropical trees are back and work fine! Thanks again, I'm really amazed how fast you fixed the mod!
